spring:
  application:
    name: pass-web
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false